log:
  level: debug
  disable_sentry: true

db:
  url: postgres://ilab1:ilab1@localhost:5432/ilab1?sslmode=disable

mvc:
  templates_dir: ./internal/service/mvc/views/templates

atm:
  public_key_path: ./atm_signing_key.pub.dev

jwt:
  signing_key_path: ./jwt_signing_key.dev
  expiry: 3600s

listener:
  addr: :8000
