version: '3.8'

services:
  migrations:
    image: lab1:latest
    container_name: migrations
    environment:
      - KV_VIPER_FILE=/app/config.yaml
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./config.yaml:/app/config.yaml
    command: ["migrate", "${MIGRATE_DIRECTION:-up}"]

  lab1:
    image: lab1:latest
    container_name: lab1
    environment:
      - KV_VIPER_FILE=/app/config.yaml
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./internal/service/mvc/views/templates:/app/templates
      - ./atm_signing_key.pub.dev:/app/atm_signing_key.pub.dev
      - ./jwt_signing_key.dev:/app/jwt_signing_key.dev
    command: ["run", "service"]
    ports:
      - "8080:8080"

  db:
    image: postgres:14.5
    hostname: lab1db
    container_name: lab1-db
    environment:
      - POSTGRES_USER=ilab1
      - POSTGRES_PASSWORD=ilab1
      - POSTGRES_DB=ilab1
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ilab1" ]
      interval: 2s
      timeout: 1s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  lab1: